### ISSUE TITLE
YAML file with start and goal queries for generate.launch not working

### ISSUE THREAD

**Issue by Harinaathgobi** [KavrakiLab/motion_bench_maker#3]
The following command given in README does not generate trajectories as the YAML file with start and goal queries is not working

`roslaunch motion_bench_maker generate.launch sensed:=true config:="package://motion_bench_maker/configs/problems/box_fetch.yaml" dataset:="package://motion_bench_maker/problems/box_fetch/"`

![image](https://user-images.githubusercontent.com/30602947/162529071-833e2a2e-8968-4929-9633-9cd472dbca68.png)

**Comment by ChamzasKonstantinos** [comment]
Hi @Harinaathgobi  thanks for reporting this. This was caused from a recent change that happened in MoveIt. The fix needs to be implemented in the main [robowlfex_library](https://github.com/KavrakiLab/robowflex). I added hotfix for now in this [branch](https://github.com/KavrakiLab/robowflex/tree/pose-new-entry-hotfix) of robowflex. It should fix the issue for now and it will probably get merged soon. Let me know if that robowflex branch works for you. 

Best, 
Constantinos

**Comment by ChamzasKonstantinos** [comment]
We merged the PR in robowflex so if you update that repo it should work, so closing this issue.
